"use client";

import { useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import dynamic from "next/dynamic";

const TikTokDownloader=dynamic(()=>import("../components/TikTokDownloader"),{ssr:false});
const DownloadAdModal=dynamic(()=>import("../components/DownloadAdModal"),{ssr:false});
const AuthModal=dynamic(()=>import("../components/AuthModal"),{ssr:false});
import { getWallzySupabase } from "../lib/wallpaper-client";

function WallzyAd({size}:{size:"320x50"|"300x250"}){const [ready,setReady]=useState(false);const cfg=size==="320x50"?{w:320,h:50,key:"2c49a0e222fe3b51d12473cd1592ca66",src:"https://www.highrevenueformat.com/2c49a0e222fe3b51d12473cd1592ca66/invoke.js"}:{w:300,h:250,key:"d57e1d0e6497dfaa47e074d39d673693",src:"https://pl31436544.profitableratecpmnetwork.com/d57e1d0e6497dfaa47e074d39d673693/invoke.js"};const srcDoc=size==="320x50"?`<!DOCTYPE html><html><body style="margin:0;overflow:hidden"><script>atOptions={'key':'${cfg.key}','format':'iframe','height':50,'width':320,'params':{}};</script><script src="${cfg.src}"></script></body></html>`:`<!DOCTYPE html><html><body style="margin:0;overflow:hidden"><script async="async" data-cfasync="false" src="${cfg.src}"></script><div id="container-${cfg.key}"></div></body></html>`;return <div className={size==="320x50"?"wallzy-ad-frame-320":"wallzy-ad-frame-300"}><div className="wallzy-ad-frame-inner"><iframe title="Advertisement" width={cfg.w} height={cfg.h} loading="lazy" sandbox="allow-scripts allow-same-origin allow-popups" srcDoc={srcDoc} style={{width:cfg.w,height:cfg.h,border:0}} scrolling="no"/></div></div>}

export default function TikTokPageClient(){const router=useRouter();const [message,setMessage]=useState("");const [user,setUser]=useState<any>(null);const [authOpen,setAuthOpen]=useState(false);const [download,setDownload]=useState<{url:string;name:string}|null>(null);const [ad,setAd]=useState({open:false,seconds:5,ready:false});
const accountLabel=user?.user_metadata?.full_name?.split(" ")[0]||"Account";
useEffect(()=>{const sb=getWallzySupabase();sb.auth.getSession().then(({data:{session}})=>setUser(session?.user||null));const sub=sb.auth.onAuthStateChange((_e,s)=>setUser(s?.user||null)).data.subscription;return()=>sub.unsubscribe()},[]);
const handleLogin=async()=>{const {error}=await getWallzySupabase().auth.signInWithOAuth({provider:"google",options:{redirectTo:window.location.href}});if(error)setMessage("Login failed: "+error.message)};
const handleLogout=async()=>{await getWallzySupabase().auth.signOut();setAuthOpen(false)};
const openDownload=(url:string,name:string)=>{setDownload({url,name});setAd({open:true,seconds:5,ready:false})};
const confirmDownload=()=>{const p=download;if(!ad.ready||!p)return;window.location.assign(p.url);setDownload(null);setAd({open:false,seconds:5,ready:false})};
return <main className="min-h-[100dvh] bg-black text-white"><header className="border-b border-white/10 bg-black/95 backdrop-blur-xl px-5 py-3.5 flex items-center justify-between"><button type="button" onClick={()=>router.push("/")} className="w-9 h-9 rounded-full bg-[#121215] border border-white/10 flex items-center justify-center"><i className="fa-solid fa-arrow-left text-xs"/></button><div className="text-center"><h1 className="text-sm font-bold">TikTok</h1><p className="text-[9px] text-white/35">Photo Downloader</p></div><button type="button" onClick={()=>setAuthOpen(true)} className="px-3 py-1.5 rounded-full bg-[#121215] border border-white/10 text-gray-200 text-xs font-semibold"><i className="fa-solid fa-user-circle mr-1.5"/>{accountLabel}</button></header><section className="px-5 pt-4 pb-10"><div className="flex justify-center mb-3"><WallzyAd size="320x50"/></div><TikTokDownloader onMessage={setMessage} onDownload={openDownload}/><div className="mt-8 flex justify-center"><WallzyAd size="300x250"/></div><div className="w-full flex justify-center items-center pt-[30px] pb-8"><div className="flex items-center justify-center gap-3 text-[15px] text-white/70 font-bold"><a href="/terms">Terms of Use</a><span>|</span><a href="/privacy">Privacy Policy</a><span>|</span><a href="/contact">Contact</a></div></div></section><BottomNav router={router}/>{authOpen&&<AuthModal user={user} onClose={()=>setAuthOpen(false)} onLogin={handleLogin} onLogout={handleLogout}/>}{ad.open&&<DownloadAdModal open seconds={ad.seconds} ready={ad.ready} onClose={()=>{if(ad.ready)setAd({open:false,seconds:5,ready:false})}} onDownload={confirmDownload}/>} {message&&<div className="fixed inset-0 z-[1700] bg-black/70 flex items-center justify-center p-5"><div className="bg-[#0a0a0c] border border-white/10 rounded-3xl p-5 w-full max-w-xs text-center"><p className="text-xs">{message}</p><button onClick={()=>setMessage("")} className="mt-4 w-full bg-white text-black rounded-2xl py-2.5 text-xs font-semibold">Got it</button></div></div>}</main>}
function BottomNav({router}:{router:any}){return <footer className="fixed bottom-[20px] inset-x-6 z-40 bg-[#0a0a0c]/90 backdrop-blur-xl border border-white/10 py-2.5 px-6 flex justify-around items-center rounded-full shadow-2xl">{[["/","fa-regular fa-compass","Explore"],["/favorites","fa-regular fa-heart","Favorites"],["/studio","fa-solid fa-palette","Studio"],["/tiktok","fa-brands fa-tiktok","TikTok"]].map(([path,icon,label],i)=><div key={path} className="contents">{i>0&&<div className="w-px h-4 bg-white/10"/>}<button type="button" onClick={()=>router.push(path)} className={"flex flex-col items-center space-y-0.5 "+(path==="/tiktok"?"text-white":"text-gray-400")}><i className={icon+" text-xs"}/><span className="text-[9px] font-semibold">{label}</span></button></div>)}</footer>}
