"use client";
import { useEffect,useMemo,useRef,useState } from "react";
import { useRouter } from "next/navigation";
import WallpaperGrid from "../components/WallpaperGrid";
import AuthModal from "../components/AuthModal";
import InstallModal from "../components/InstallModal";
import BottomNav from "../components/BottomNav";
import LoadingScreen from "../components/LoadingScreen";
import {createWallzyLoader,getWallzySupabase,loadWallzyCategories,loadWallzyFavorites,saveWallzyFavorites} from "../lib/wallpaper-client";

const slugify=(v:string)=>String(v||"all").normalize("NFD").replace(/[\\u0300-\\u036f]/g,"").toLowerCase().trim().replace(/[^a-z0-9]+/g,"-").replace(/^-+|-+$/g,"")||"all";

function Ad({size}:{size:"320x50"|"300x250"}){const[ready,setReady]=useState(false);useEffect(()=>{const t=setTimeout(()=>setReady(true),size==="320x50"?1200:2200);return()=>clearTimeout(t)},[size]);const c=size==="320x50"?{w:320,h:50,key:"2c49a0e222fe3b51d12473cd1592ca66",p:"highrevenue"}:{w:300,h:250,key:"d57e1d0e6497dfaa47e074d39d673693",p:"profitablerate"};const src=c.p==="highrevenue"?"<script>atOptions={key:\"" + c.key + "\",format:\"iframe\",height:" + c.h + ",width:" + c.w + ",params:{}};</script><script src=\"https://www.highrevenueformat.com/" + c.key + "/invoke.js\"></script>":"<script async=\"async\" data-cfasync=\"false\" src=\"https://pl31436544.profitableratecpmnetwork.com/" + c.key + "/invoke.js\"></script><div id=\"container-" + c.key + "\"></div>";return <div className={size==="320x50"?"wallzy-ad-frame-320":"wallzy-ad-frame-300"}><div className="wallzy-ad-frame-inner">{ready&&<iframe title="Advertisement" width={c.w} height={c.h} loading="lazy" sandbox="allow-scripts allow-same-origin allow-popups" srcDoc={"<!DOCTYPE html><html><body style=\"margin:0;overflow:hidden\">" + src + "</body></html>"} style={{width:c.w,height:c.h,border:0}} scrolling="no"/>}</div></div>}

function Header({title,user,onInstall,onAuth}:{title:string;user:any;onInstall:()=>void;onAuth:()=>void}){const name=user?.user_metadata?.full_name?.split(" ")[0]||"Account";return <header className="relative z-40 bg-[#000000]/90 backdrop-blur-xl px-5 py-3.5 flex justify-between items-center border-b border-white/10"><div className="flex items-center min-w-0"><button type="button" onClick={()=>history.back()} className="w-9 h-9 rounded-full bg-[#121215] border border-white/10 flex items-center justify-center mr-2"><i className="fa-solid fa-arrow-left text-xs"/></button><span className="font-bold text-lg tracking-tight text-white truncate">{title}</span></div><div className="flex items-center space-x-2 shrink-0"><button type="button" onClick={onInstall} className="w-9 h-9 rounded-full bg-[#121215] border border-white/10 flex items-center justify-center" title="Install"><i className="fa-solid fa-mobile-screen-button text-xs"/></button><button type="button" onClick={onAuth} className="px-3 py-1.5 rounded-full bg-[#121215] text-gray-200 text-xs font-semibold flex items-center space-x-1.5 border border-white/10"><i className="fa-solid fa-user-circle text-xs"/><span>{name}</span></button></div></header>}

function CategoryNav({categories,active}:{categories:string[];active:string}){const router=useRouter();const ref=useRef<HTMLElement|null>(null);useEffect(()=>{const n=ref.current;if(!n)return;const el=Array.from(n.querySelectorAll<HTMLElement>(".cat-btn")).find(x=>x.dataset.category?.toLowerCase()===active.toLowerCase());if(el)n.scrollTo({left:Math.max(0,el.offsetLeft-(n.clientWidth-el.offsetWidth)/2),behavior:"smooth"})},[active,categories]);return <nav ref={ref} className="w-full min-w-0 px-5 py-2.5 flex flex-nowrap gap-2 overflow-x-auto overscroll-x-contain touch-pan-x scrollbar-none bg-transparent">{["all",...categories].map(v=><button key={v} data-category={v} type="button" onClick={()=>router.push(v==="all"?"/":"/category/"+slugify(v))} className={active.toLowerCase()===v.toLowerCase()?"cat-btn inline-flex w-max min-w-max shrink-0 bg-white text-black shadow-sm px-4 py-2 rounded-full text-xs font-semibold whitespace-nowrap transition":"cat-btn inline-flex w-max min-w-max shrink-0 bg-[#121215] text-gray-400 border border-white/10 px-4 py-2 rounded-full text-xs font-semibold whitespace-nowrap transition"}>{v==="all"?"#All Wallpapers":"#"+v}</button>)}</nav>}

function Footer(){return <div className="w-full flex justify-center items-center pt-[30px] pb-8"><div className="flex items-center gap-3 text-[15px] text-white/70 font-bold"><a href="/terms">Terms of Use</a><span>|</span><a href="/privacy">Privacy Policy</a><span>|</span><a href="/contact">Contact</a></div></div>}
export default function CategoryPageClient({category}:{category:string}){const router=useRouter(),mainRef=useRef<HTMLElement|null>(null),sbRef=useRef<any>(null),userRef=useRef<any>(null);const[categories,setCategories]=useState<string[]>([]),[user,setUser]=useState<any>(null),[favorites,setFavorites]=useState<any[]>([]),[items,setItems]=useState<any[]>([]),[hasMore,setHasMore]=useState(false),[loading,setLoading]=useState(true),[loadingMore,setLoadingMore]=useState(false),[nextOffset,setNextOffset]=useState(0),[authModal,setAuthModal]=useState(false),[installModal,setInstallModal]=useState(false);
useEffect(()=>{let dead=false;(async()=>{try{const sb=getWallzySupabase();sbRef.current=sb;const[{data:{session}},cats]=await Promise.all([sb.auth.getSession(),loadWallzyCategories(sb)]);if(dead)return;await new Promise(resolve=>setTimeout(resolve,350));if(dead)return;setCategories(cats);const u=session?.user||null;userRef.current=u;setUser(u);if(u)setFavorites(await loadWallzyFavorites(sb,u));const actual=cats.find(x=>x.toLowerCase()===category.toLowerCase())||category;const page=await createWallzyLoader(sb,actual,{randomize:false,initialOffset:0,pageSize:20})();if(dead)return;setItems(page.images||[]);setHasMore(Boolean(page.hasMore));setNextOffset(Number(page.nextOffset||page.images?.length||0));}catch(e){console.error("[Wallzy] Category load failed:",e)}finally{if(!dead)setLoading(false)}})();return()=>{dead=true}},[category]);
useEffect(()=>{if(!sbRef.current)return;const{data}=sbRef.current.auth.onAuthStateChange(async(_:any,s:any)=>{const u=s?.user||null;userRef.current=u;setUser(u);setFavorites(u?await loadWallzyFavorites(sbRef.current,u):[])});return()=>data.subscription.unsubscribe()},[]);
const toggleFavorite=async(id:string)=>{const u=userRef.current;if(!u){setAuthModal(true);return}const w=items.find(x=>String(x.id)===String(id));if(!w)return;const next=favorites.some(x=>String(x.id)===String(id))?favorites.filter(x=>String(x.id)!==String(id)):[...favorites,w];setFavorites(next);try{await saveWallzyFavorites(sbRef.current,u,next)}catch{setFavorites(favorites)}};
const loadMore=async()=>{if(loadingMore||!hasMore)return;setLoadingMore(true);try{const page=await createWallzyLoader(sbRef.current,category,{randomize:false,initialOffset:nextOffset,pageSize:20})();setItems(v=>[...v,...(page.images||[])]);setHasMore(Boolean(page.hasMore));setNextOffset(Number(page.nextOffset||nextOffset))}finally{setLoadingMore(false)}};
const view=useMemo(()=>({mode:"explore",items,favorites,displayedCount:items.length,hasMore,loading,loadingMore}),[items,favorites,hasMore,loading,loadingMore]);
const login=async()=>{try{const{error}=await sbRef.current.auth.signInWithOAuth({provider:"google",options:{redirectTo:window.location.origin+window.location.pathname}});if(error)throw error}catch(e){console.error(e)}};const logout=async()=>{await sbRef.current?.auth.signOut();setAuthModal(false)};
return <>{loading&&<LoadingScreen />}<div className="w-full min-w-0 max-w-none h-[100dvh] shadow-2xl overflow-hidden flex flex-col relative bg-[#000000]"><main ref={mainRef} className="flex-1 pb-36 overflow-y-auto scrollbar-none bg-transparent"><Header title={category} user={user} onInstall={()=>setInstallModal(true)} onAuth={()=>setAuthModal(true)}/><button type="button" onClick={()=>router.push("/search")} className="w-full px-5 pt-3 pb-1 bg-transparent text-left"><div className="relative flex items-center"><i className="fa-solid fa-magnifying-glass absolute left-3.5 text-gray-400 text-xs"/><div className="w-full bg-[#0a0a0c] border border-white/10 rounded-2xl py-2.5 pl-10 pr-9 text-[16px] sm:text-xs text-white/80 shadow-inner">Search keywords, categories, tags...</div></div></button><div className="sticky top-0 z-[35] bg-[#000000]/90 backdrop-blur-xl">{categories.length>0?<CategoryNav categories={categories} active={category}/>:<nav className="w-full min-w-0 px-5 py-2.5 flex flex-nowrap gap-2 overflow-hidden overscroll-x-contain scrollbar-none bg-transparent" aria-hidden="true">{[140,128,116,138,124,132].map((w,i)=><div key={i} style={{width:w}} className="relative h-9 shrink-0 overflow-hidden rounded-full border border-white/10 bg-[#0a0a0c]"><div className="absolute inset-0 skeleton-wave" /></div>)}</nav>}</div><Ad size="320x50"/><WallpaperGrid view={view} hideFavorite onNavigate={w=>{try{sessionStorage.setItem("wallzy:return-url",window.location.href);sessionStorage.setItem("wallzy:return-scroll",String(mainRef.current?.scrollTop||0))}catch{}router.push("/wallpaper/"+encodeURIComponent(String(w.id)))}} onToggleFavorite={toggleFavorite} onLoadMore={loadMore} onExplore={()=>router.push("/")}/><Footer/><Ad size="300x250"/></main><BottomNav active="explore" /></div>{installModal&&<InstallModal onClose={()=>setInstallModal(false)}/>} {authModal&&<AuthModal user={user} onClose={()=>setAuthModal(false)} onLogin={login} onLogout={logout}/>}</>}
